version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.base
    ports:
      - "8000:8000"
    env_file:
      - ../../env/production.env
    depends_on:
      - mongodb
    networks:
      - duso-network
    restart: unless-stopped
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - duso-network
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  duso-network:
    driver: bridge

volumes:
  mongodb_data: 